Instance: encounter-example-hypo-hypo
InstanceOf: AcuteCareHospitalMonthlyReportingEncounter
Title: "Encounter - Hypo Encounter Example Hypo"
Description: "Encounter - Example Hypo Encounter Hypo"
Usage: #example
* meta.profile[1] = "http://www.cdc.gov/nhsn/fhirportal/dqm/ig/StructureDefinition/hypoglycemic-reporting-encounter"
* identifier.use = #usual
* identifier.system = "urn:oid:2.16.840.1.113883.19.5.1.698.8"
* identifier.value = "1000510425"
* status = #finished
* status.extension.url = "http://www.cdc.gov/nhsn/fhirportal/dqm/ig/StructureDefinition/link-original-element-value-extension"
* status.extension.valueString = "TRIAGED"
* class = $v3-ActCode#IMP "inpatient encounter"
* type = $sct#2421000175108 "Acute care inpatient service"
* type.text = "Acute care inpatient"
* subject.reference = "Patient/patient-example-hypo"
* subject.display = "Hypo, Edadd"
* participant[0].type = $v3-ParticipationType#ADM "admitter"
* participant[=].type.text = "admitter"
* participant[=].individual.type = "Practitioner"
* participant[=].individual.display = "Faculty Physician Um_Cln, MD"
* participant[+].type = $v3-ParticipationType#DIS "discharger"
* participant[=].type.text = "discharger"
* participant[=].individual.type = "Practitioner"
* participant[=].individual.display = "Faculty Physician Um_Cln, MD"
* participant[+].type = $v3-ParticipationType#ATND "attender"
* participant[=].type.text = "attender"
* participant[=].period.start = "2022-08-17T16:59:38Z"
* participant[=].period.end = "2022-08-22T19:09:00Z"
* participant[=].individual.type = "Practitioner"
* participant[=].individual.display = "Faculty Physician Um_Cln, MD"
* period.start = "2022-08-17T16:25:00Z"
* period.end = "2022-08-22T19:09:00Z"
* reasonCode = $sct#80394007 "Hyperglycemia (disorder)"
* reasonCode.text = "Hyperglycemia"
* diagnosis.condition.display = "Hyperglycemia"
* account.identifier.system = "urn:oid:2.16.840.1.113883.19.5.1.3.726"
* account.identifier.value = "100066850"
* account.display = "HYPO,EDADD"
* hospitalization.admitSource = $admit-source#nursing "From nursing home"
* hospitalization.admitSource.text = "From nursing home"
* hospitalization.dischargeDisposition = $discharge-disposition#snf "Skilled nursing facility"
* hospitalization.dischargeDisposition.text = "Skilled nursing facility"
//* location[0].location.display = "UH Adult Emergency Department"
* location[0].location.display = "EMERGENCY - PAVILION"
* location[=].location = Reference(location-example-hypo-emergency)
* location[=].period.start = "2022-08-17T16:25:00Z"
* location[=].period.end = "2022-08-17T17:01:00Z"
//* location[+].location.display = "UH 7C MED ACUTE CARE"
* location[+].location.display = "Health Hospital Location"
* location[=].location = Reference(location-example-hypo-hospital)
* location[=].period.start = "2022-08-17T17:01:00Z"
* location[=].period.end = "2022-08-22T19:09:00Z"
/* location[+].location.display = "7153"
* location[=].physicalType = $location-physical-type#ro "Room"
* location[=].physicalType.text = "Room"
* location[=].period.start = "2022-08-17T16:25:00Z"
* location[=].period.end = "2022-08-17T17:01:00Z"
* location[+].location.identifier.system = "urn:oid:2.16.840.1.113883.19.5.1.6669"
* location[=].location.identifier.value = "1445"
* location[=].location.display = "7153 / 01"
* location[=].physicalType = $location-physical-type#bd "Bed"
* location[=].physicalType.text = "Bed"
* location[=].period.start = "2022-08-17T17:01:00Z"
* location[=].period.end = "2022-08-22T19:09:00Z"
*/