# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tags: |
    latest
    $(Build.BuildId)

stages:
- stage: Build
  displayName: Build & Push Measure Builder
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'LCG Docker HUB'
        repository: 'lantanagroup/measure-builder'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.builder'
        tags: |
          latest
          $(Build.BuildId)