[IG]
#ig = input/gov.cdc.nhsn.measures.xml
ig = fsh-generated/resources/ImplementationGuide-gov.cdc.nhsn.measures.json
template = custom-template
usage-stats-opt-out = true #  # Opt out for regular building. Should opt in for final publication. in sushi-config as well
fhir-version=4.0.1