Instance: measurereport-example-individual-ach-monthly-pass2
InstanceOf: MeasureReport
Title: "MeasureReport - Example Individual ACH Monthly Pass2 - Hypo"
Description: "MeasureReport - Example Individual ACH Monthly Pass2 - Hypoglycemia"
Usage: #example
* meta.profile = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/indv-measurereport-deqm"
* identifier.system = "http://example.org/fhir/measurereport/id"
* identifier.value = "123456789-pass2"

* extension[0].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-measureScoring"
* extension[=].valueCodeableConcept = $measure-scoring#cohort
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description"
//* extension[=].valueString = "The Acute Care Hospital Initial Population includes all encounters for patients of any age in an ED, observation, or inpatient location or all encounters for patients of any age with an ED, observation, inpatient, or short stay status during the measurement period."
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-minimal-patient"
* extension[=].valueReference = Reference(patient-example-ach-monthly-pass2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-encounter"
* extension[=].valueReference = Reference(encounter-example-ach-monthly-pass2-emergency)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-encounter"
* extension[=].valueReference = Reference(encounter-example-ach-monthly-pass2-inpatient)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-coverage"
* extension[=].valueReference = Reference(coverage-example-ach-monthly-pass2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-condition"
* extension[=].valueReference = Reference(condition-example-diagnosis-ach-monthly-pass2-problem)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-condition"
* extension[=].valueReference = Reference(condition-example-diagnosis-ach-monthly-pass2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-device"
* extension[=].valueReference = Reference(device-example-ach-monthly-pass2-compress-hose)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-diagnosticreport-lab"
* extension[=].valueReference = Reference(diagnosticreport-example-ach-monthly-pass2-radiology)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medadmin-example-ach-monthly-pass2-dex4)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medadmin-example-ach-monthly-pass2-heparin-1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medadmin-example-ach-monthly-pass2-heparin-2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-3)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-4)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(medicationrequest-example-ach-monthly-pass2-dex4-tablet)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(medicationrequest-example-ach-monthly-pass2-heparin)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(medicationrequest-example-ach-monthly-pass2-insulin-lispro)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(medicationrequest-example-ach-monthly-pass2-metformin)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-lab-category"
* extension[=].valueReference = Reference(observation-example-ach-monthly-pass2-aptt)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-lab-category"
* extension[=].valueReference = Reference(observation-example-ach-monthly-pass2-poc-1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-lab-category"
* extension[=].valueReference = Reference(observation-example-ach-monthly-pass2-poc-2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-lab-category"
* extension[=].valueReference = Reference(observation-example-ach-monthly-pass2-hemo-a1c)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-lab-category"
* extension[=].valueReference = Reference(observation-example-ach-monthly-pass2-hemo)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-vital-signs"
* extension[=].valueReference = Reference(observation-example-ach-monthly-pass2-vitals-weight)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-procedure"
* extension[=].valueReference = Reference(procedure-example-ach-monthly-pass2-ivcf)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-service-request"
* extension[=].valueReference = Reference(servicerequest-example-ach-monthly-pass2-aptt)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-service-request"
* extension[=].valueReference = Reference(servicerequest-example-ach-monthly-pass2-glucose)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-service-request"
* extension[=].valueReference = Reference(servicerequest-example-ach-monthly-pass2-hemo-a1c)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-service-request"
* extension[=].valueReference = Reference(servicerequest-example-ach-monthly-pass2-hemo)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-specimen"
* extension[=].valueReference = Reference(specimen-example-ach-monthly-pass2-blood-1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-specimen"
* extension[=].valueReference = Reference(specimen-example-ach-monthly-pass2-blood-2)
* status = #complete
* type = #individual
* measure = "http://www.cdc.gov/nhsn/fhirportal/dqm/ig/Measure/NHSNAcuteCareHospitalMonthlyInitialPopulation|1.0.0-cibuild"
* subject = Reference(patient-example-ach-monthly-pass1)
* date = "2024-02-05T21:04:29.481+00:00"
* reporter = Reference(organization-example-submitting-organization)
* period.start = "2024-01-05T00:00:00.000+00:00"
* period.end = "2024-02-04T00:00:00.000+00:00"
* improvementNotation = $measure-improvement-notation#increase
//* group.measureScore.extension.url = "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
//* group.measureScore.extension.valueCode = #unknown
//* group.population.extension.url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description"
//* group.population.extension.valueString = "All inpatient encounters (including ED/Observation visits that end within one hour of the start of the inpatient encounter) during the measurement period for patients of all ages in which at least one diabetic medication was ordered or administered during the encounter."
* group.population.code = $measure-population#initial-population "Initial Population"
* group.population.count = 1
* evaluatedResource[0] = Reference(patient-example-ach-monthly-pass2)
* evaluatedResource[0] = Reference(encounter-example-ach-monthly-pass2-emergency)
* evaluatedResource[0] = Reference(encounter-example-ach-monthly-pass2-inpatient)
* evaluatedResource[0] = Reference(coverage-example-ach-monthly-pass2)
* evaluatedResource[0] = Reference(condition-example-diagnosis-ach-monthly-pass2-problem)
* evaluatedResource[0] = Reference(condition-example-diagnosis-ach-monthly-pass2)
* evaluatedResource[0] = Reference(device-example-ach-monthly-pass2-compress-hose)
* evaluatedResource[0] = Reference(diagnosticreport-example-ach-monthly-pass2-radiology)
* evaluatedResource[0] = Reference(medadmin-example-ach-monthly-pass2-dex4)
* evaluatedResource[0] = Reference(medadmin-example-ach-monthly-pass2-heparin-1)
* evaluatedResource[0] = Reference(medadmin-example-ach-monthly-pass2-heparin-2)
* evaluatedResource[0] = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-1)
* evaluatedResource[0] = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-2)
* evaluatedResource[0] = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-3)
* evaluatedResource[0] = Reference(medadmin-example-ach-monthly-pass2-insulin-lispro-4)
* evaluatedResource[0] = Reference(medicationrequest-example-ach-monthly-pass2-dex4-tablet)
* evaluatedResource[0] = Reference(medicationrequest-example-ach-monthly-pass2-heparin)
* evaluatedResource[0] = Reference(medicationrequest-example-ach-monthly-pass2-insulin-lispro)
* evaluatedResource[0] = Reference(medicationrequest-example-ach-monthly-pass2-metformin)
* evaluatedResource[0] = Reference(observation-example-ach-monthly-pass2-aptt)
* evaluatedResource[0] = Reference(observation-example-ach-monthly-pass2-poc-1)
* evaluatedResource[0] = Reference(observation-example-ach-monthly-pass2-poc-2)
* evaluatedResource[0] = Reference(observation-example-ach-monthly-pass2-hemo-a1c)
* evaluatedResource[0] = Reference(observation-example-ach-monthly-pass2-hemo)
* evaluatedResource[0] = Reference(observation-example-ach-monthly-pass2-vitals-weight)
* evaluatedResource[0] = Reference(procedure-example-ach-monthly-pass2-ivcf)
* evaluatedResource[0] = Reference(servicerequest-example-ach-monthly-pass2-aptt)
* evaluatedResource[0] = Reference(servicerequest-example-ach-monthly-pass2-glucose)
* evaluatedResource[0] = Reference(servicerequest-example-ach-monthly-pass2-hemo-a1c)
* evaluatedResource[0] = Reference(servicerequest-example-ach-monthly-pass2-hemo)
* evaluatedResource[0] = Reference(specimen-example-ach-monthly-pass2-blood-1)
* evaluatedResource[0] = Reference(specimen-example-ach-monthly-pass2-blood-2)