Instance: bundle-example-ach-daily-full
InstanceOf: NHSNMeasureReportBundleProfile
Title: "Full ACH Daily Measure Submission Bundle"
Description: "Measure Bundle - Full ACH Daily Measure Submission Example"
Usage: #example
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:1eaddf4c-2ec0-4dc4-b26f-9586d7a7bbb3"
* type = #collection
* timestamp = "2022-11-15T21:04:29.481+00:00"
* entry[0].fullUrl = "http://nhsnlink.org/fhir/Organization/organization-example-submitting-organization"
* entry[=].resource = organization-example-submitting-organization
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Device/device-example-submitting-device"
* entry[=].resource = device-example-submitting-device
* entry[+].fullUrl = "http://nhsnlink.org/fhir/List/list-example-ach-daily-patients-of-interest"
* entry[=].resource = list-example-ach-daily-patients-of-interest
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-ach-daily-subjectlist"
* entry[=].resource = measurereport-example-ach-daily-subjectlist
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-ach-daily-initialpopulationpass"
* entry[=].resource = measurereport-example-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Patient/patient-example-ach-daily-initialpopulationpass"
* entry[=].resource = patient-example-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-ach-daily-initialpopulationpass-1"
* entry[=].resource = encounter-example-ach-daily-initialpopulationpass-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-ach-daily-initialpopulationpass-2"
* entry[=].resource = encounter-example-ach-daily-initialpopulationpass-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Coverage/coverage-example-ach-daily-initialpopulationpass"
* entry[=].resource = coverage-example-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-ach-daily-initialpopulationpass"
* entry[=].resource = condition-example-diagnosis-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationAdministration/medadmin-example-ach-daily-initialpopulationpass-1"
* entry[=].resource = medadmin-example-ach-daily-initialpopulationpass-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-ach-daily-initialpopulationpass"
* entry[=].resource = medicationrequest-example-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationAdministration/medadmin-example-ach-daily-initialpopulationpass-2"
* entry[=].resource = medadmin-example-ach-daily-initialpopulationpass-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/lab-observation-example-ach-daily-initialpopulationpass"
* entry[=].resource = lab-observation-example-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/ServiceRequest/servicerequest-example-ach-daily-initialpopulationpass-covid"
* entry[=].resource = servicerequest-example-ach-daily-initialpopulationpass-covid
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Specimen/specimen-example-ach-daily-initialpopulationpass"
* entry[=].resource = specimen-example-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-ach-daily-negativepcr"
* entry[=].resource = measurereport-example-ach-daily-negativepcr
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Patient/patient-example-ach-daily-negativepcr"
* entry[=].resource = patient-example-ach-daily-negativepcr
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-ach-daily-negativepcr-1"
* entry[=].resource = encounter-example-ach-daily-negativepcr-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-ach-daily-negativepcr-2"
* entry[=].resource = encounter-example-ach-daily-negativepcr-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Coverage/coverage-example-ach-daily-negativepcr"
* entry[=].resource = coverage-example-ach-daily-negativepcr
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-ach-daily-negativepcr"
* entry[=].resource = condition-example-diagnosis-ach-daily-negativepcr
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationAdministration/medadmin-example-ach-daily-negativepcr"
* entry[=].resource = medadmin-example-ach-daily-negativepcr
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-ach-daily-negativepcr"
* entry[=].resource = medicationrequest-example-ach-daily-negativepcr
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/lab-observation-example-ach-daily-negativepcr-1"
* entry[=].resource = lab-observation-example-ach-daily-negativepcr-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/lab-observation-example-ach-daily-negativepcr-2"
* entry[=].resource = lab-observation-example-ach-daily-negativepcr-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/ServiceRequest/servicerequest-example-ach-daily-negativepcr-covid-1"
* entry[=].resource = servicerequest-example-ach-daily-negativepcr-covid-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/ServiceRequest/servicerequest-example-ach-daily-negativepcr-covid-2"
* entry[=].resource = servicerequest-example-ach-daily-negativepcr-covid-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Specimen/specimen-example-ach-daily-negativepcr-1"
* entry[=].resource = specimen-example-ach-daily-negativepcr-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Specimen/specimen-example-ach-daily-negativepcr-2"
* entry[=].resource = specimen-example-ach-daily-negativepcr-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Procedure/procedure-example-ach-daily-negativepcr-intubation"
* entry[=].resource = procedure-example-ach-daily-negativepcr-intubation
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-ach-daily-influenzatherapeutic"
* entry[=].resource = measurereport-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Patient/patient-example-ach-daily-influenzatherapeutic"
* entry[=].resource = patient-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-ach-daily-influenzatherapeutic"
* entry[=].resource = encounter-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Coverage/coverage-example-ach-daily-influenzatherapeutic"
* entry[=].resource = coverage-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-ach-daily-influenzatherapeutic"
* entry[=].resource = condition-example-diagnosis-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationAdministration/medadmin-example-ach-daily-influenzatherapeutic"
* entry[=].resource = medadmin-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-ach-daily-influenzatherapeutic"
* entry[=].resource = medicationrequest-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Immunization/immunization-example-ach-daily-influenzatherapeutic"
* entry[=].resource = immunization-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-ach-daily-rsvlabbtg"
* entry[=].resource = measurereport-example-ach-daily-rsvlabbtg
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Patient/patient-example-ach-daily-rsvlabbtg"
* entry[=].resource = patient-example-ach-daily-rsvlabbtg
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-ach-daily-rsvlabbtg"
* entry[=].resource = encounter-example-ach-daily-rsvlabbtg
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Coverage/coverage-example-ach-daily-rsvlabbtg"
* entry[=].resource = coverage-example-ach-daily-rsvlabbtg
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-ach-daily-rsvlabbtg"
* entry[=].resource = condition-example-diagnosis-ach-daily-rsvlabbtg
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationAdministration/medadmin-example-ach-daily-rsvlabbtg-1"
* entry[=].resource = medadmin-example-ach-daily-rsvlabbtg-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-ach-daily-rsvlabbtg-1"
* entry[=].resource = medicationrequest-example-ach-daily-rsvlabbtg-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationAdministration/medadmin-example-ach-daily-rsvlabbtg-2"
* entry[=].resource = medadmin-example-ach-daily-rsvlabbtg-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-ach-daily-rsvlabbtg-2"
* entry[=].resource = medicationrequest-example-ach-daily-rsvlabbtg-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/lab-observation-example-ach-daily-rsvlabbtg"
* entry[=].resource = lab-observation-example-ach-daily-rsvlabbtg
* entry[+].fullUrl = "http://nhsnlink.org/fhir/ServiceRequest/servicerequest-example-ach-daily-rsvlabbtg-rsv"
* entry[=].resource = servicerequest-example-ach-daily-rsvlabbtg-rsv
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Specimen/specimen-example-ach-daily-rsvlabbtg"
* entry[=].resource = specimen-example-ach-daily-rsvlabbtg

// Added resources that were missing from the bundle
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-ach-daily-initialpopulationpass"
* entry[=].resource = medication-example-ach-daily-initialpopulationpass
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-ach-daily-negativepcr"
* entry[=].resource = medication-example-ach-daily-negativepcr
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-ach-daily-influenzatherapeutic"
* entry[=].resource = medication-example-ach-daily-influenzatherapeutic
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-ach-daily-rsvlabbtg-1"
* entry[=].resource = medication-example-ach-daily-rsvlabbtg-1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-ach-daily-rsvlabbtg-2"
* entry[=].resource = medication-example-ach-daily-rsvlabbtg-2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Location/location-example-ach-daily-emergency"
* entry[=].resource = location-example-ach-daily-emergency
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Location/location-example-ach-daily-hospital"
* entry[=].resource = location-example-ach-daily-hospital
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Location/location-example-ach-daily-inpatient"
* entry[=].resource = location-example-ach-daily-inpatient
