Instance: medicationrequest-example-rps-initialpopulationpass
InstanceOf: RespiratoryPathogensSurveillanceEventMedicationRequest
Usage: #example
* identifier.use = #usual
* identifier.system = "urn:oid:2.16.840.1.113883.19.5.1.798"
* identifier.value = "101903002"
* status = #completed
* intent = #order
* category = $medicationrequest-category#inpatient "Inpatient"
* category.text = "Inpatient"
* medicationReference.reference = "Medication/medication-example-rps-initialpopulationpass"
* medicationReference.display = "remdesivir 100 mg"
* subject.reference = "Patient/patient-example-rps-initialpopulationpass"
* subject.display = "RPS, InitialPopulationPass"
* encounter.reference = "Encounter/encounter-example-rps-initialpopulationpass-inpatient"
* encounter.display = "Hospital Encounter"
* authoredOn = "2024-01-14T21:30:15Z"
* requester.type = "Practitioner"
* requester.display = "Faculty Physician Um_Cln, MD"
* recorder.type = "Practitioner"
* recorder.display = "Faculty Physician Um_Cln, MD"
* courseOfTherapyType = $medicationrequest-course-of-therapy#acute "Short course (acute) therapy"
* courseOfTherapyType.text = "Short course (acute) therapy"
* dosageInstruction.text = "Remdesivir 200 mg IV once a day on day 1, then 100 mg IV once a day on days 2-5"
* dosageInstruction.timing.repeat.boundsPeriod.start = "2024-01-14T21:30:15Z"
* dosageInstruction.timing.repeat.boundsPeriod.end = "2024-01-15T21:30:15Z"
* dosageInstruction.timing.repeat.frequency = 1
* dosageInstruction.timing.repeat.period = 1
* dosageInstruction.timing.repeat.periodUnit = #d
* dosageInstruction.timing.code.text = "Remdesivir 200 mg IV once a day on day 1"
* dosageInstruction.timing.repeat.boundsPeriod.start = "2024-01-15T21:30:15Z"
* dosageInstruction.timing.repeat.boundsPeriod.end = "2024-01-19T21:30:15Z"
* dosageInstruction.timing.repeat.frequency = 4
* dosageInstruction.timing.repeat.period = 1
* dosageInstruction.timing.repeat.periodUnit = #d
* dosageInstruction.timing.code.text = "100 Remdesivir mg IV once a day on days 2-5"
* dosageInstruction.asNeededBoolean = false
* dosageInstruction.route = $sct#47625008 "Intravenous use"
* dosageInstruction.route.text = "Intravenous"