Instance: encounter-example-rps-negativepcr-2
InstanceOf: RespiratoryPathogensSurveillanceEventEncounter
Title: "Encounter - RPS Daily Encounter Example Negative PCR 2"
Description: "Encounter - Example RPS Daily Encounter Negative PCR 2"
Usage: #example
* identifier.use = #usual
* identifier.system = "urn:oid:2.16.840.1.113883.19.5.1.698.8"
* identifier.value = "123456789986"
* status = #finished
* status.extension.url = "http://www.cdc.gov/nhsn/fhirportal/dqm/ig/StructureDefinition/link-original-element-value-extension"
* status.extension.valueString = "TRIAGED"
* class = $v3-ActCode#IMP "Inpatient Encounter"
* type = $sct#453701000124103 "In-person encounter"
* type.text = "In-person encounter"
* subject.reference = "Patient/patient-example-rps-negativepcr"
* subject.display = "RPS, NegativePCR"
* period.start = "2024-01-02T06:01:00Z"
* period.end = "2024-01-16T08:30:00Z"
* reasonCode = $sct#267036007 "shortness of breath"
* reasonCode.text = "Shortness of breath"
* hospitalization.admitSource = $admit-source#outp "From outpatient department"
* hospitalization.admitSource.text = "observation unit"
* hospitalization.dischargeDisposition = $discharge-disposition#exp "Expired"
* hospitalization.dischargeDisposition.text = "Deceased (expired)"
//* location[0].location.display = "UH Adult Emergency Department"
* location[0].location.display = "EMERGENCY - PAVILION"
* location[=].location = Reference(location-example-hypo-emergency)
* location[=].period.start = "2022-08-11T18:52:00Z"
* location[=].period.end = "2022-08-17T16:09:00Z"
//* location[+].location.display = "UH 7C MED ACUTE CARE"
* location[+].location.display = "Health Hospital Location"
* location[=].location = Reference(location-example-hypo-hospital)
* location[=].period.start = "2022-08-17T16:09:00Z"
* location[=].period.end = "2022-08-22T19:01:00Z"
/* location[+].location.display = "7129"
* location[=].physicalType = $location-physical-type#ro "Room"
* location[=].physicalType.text = "Room"
* location[=].period.start = "2022-08-11T18:52:00Z"
* location[=].period.end = "2022-08-17T16:09:00Z"
* location[+].location.identifier.system = "urn:oid:2.16.840.1.113883.19.5.1.6669"
* location[=].location.identifier.value = "1405"
* location[=].location.display = "7129 / 01"
* location[=].physicalType = $location-physical-type#bd "Bed"
* location[=].physicalType.text = "Bed"
* location[=].period.start = "2022-08-17T16:09:00Z"
* location[=].period.end = "2022-08-22T19:01:00Z"
*/