Instance: measurereport-example-individual-measurereport-hypo
InstanceOf: MeasureReport
Title: "MeasureReport - Example Individual Hypo - Hypo"
Description: "MeasureReport - Example Individual Hypo - Hypoglycemia"
Usage: #example
* meta.profile = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/indv-measurereport-deqm"
//* text.status = #extensions
//* text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative: MeasureReport</b><a name=\"measurereport-example-individual-measurereport-hypo\"> </a></p><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\">Resource MeasureReport &quot;measurereport-example-individual-measurereport-hypo&quot; </p><p style=\"margin-bottom: 0px\">Profile: <a href=\"http://hl7.org/fhir/us/davinci-deqm/STU3.1/StructureDefinition-indv-measurereport-deqm.html\">DEQM Individual MeasureReport Profile</a></p></div><p><b>DEQM Measure Scoring Extension</b>: Cohort <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"http://terminology.hl7.org/5.0.0/CodeSystem-measure-scoring.html\">MeasureScoring</a>#cohort)</span></p><p><b>Measure Report Population Description (R5 surrogate extension)</b>: The Hypoglycemia Initial Population includes all inpatient encounters (including ED/Observation visits that end within one hour of the start of the inpatient encounter) during the measurement period for patients of all ages in which at least one diabetic medication was ordered or administered during the encounter.</p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo1.html\">Observation/observation-example-hypo-lab-hypo1</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Encounter-encounter-example-hypo-hypo.html\">Encounter/encounter-example-hypo-hypo</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo2.html\">Observation/observation-example-hypo-lab-hypo2</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo3.html\">Observation/observation-example-hypo-lab-hypo3</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo4.html\">Observation/observation-example-hypo-lab-hypo4</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Medication-medication-example-hypo-hypo1.html\">Medication/medication-example-hypo-hypo1</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Patient-patient-example-hypo.html\">Patient/patient-example-hypo</a> &quot; HYPO&quot;</p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Medication-medication-example-hypo-hypo2.html\">Medication/medication-example-hypo-hypo2</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"MedicationRequest-medicationrequest-example-hypo-hypo1.html\">MedicationRequest/medicationrequest-example-hypo-hypo1</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo5.html\">Observation/observation-example-hypo-lab-hypo5</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"MedicationRequest-medicationrequest-example-hypo-hypo2.html\">MedicationRequest/medicationrequest-example-hypo-hypo2</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo6.html\">Observation/observation-example-hypo-lab-hypo6</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo7.html\">Observation/observation-example-hypo-lab-hypo7</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Condition-condition-example-diagnosis-hypo1.html\">Condition/condition-example-diagnosis-hypo1</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Medication-medication-example-hypo-hypo3.html\">Medication/medication-example-hypo-hypo3</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"MedicationRequest-medicationrequest-example-hypo-hypo3.html\">MedicationRequest/medicationrequest-example-hypo-hypo3</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Observation-observation-example-hypo-lab-hypo8.html\">Observation/observation-example-hypo-lab-hypo8</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"MedicationRequest-medicationrequest-example-hypo-hypo4.html\">MedicationRequest/medicationrequest-example-hypo-hypo4</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Medication-medication-example-hypo-hypo4.html\">Medication/medication-example-hypo-hypo4</a></p><p><b>Measure Report Supplemental Data Element Reference (R5 surrogate extension)</b>: <a href=\"Condition-condition-example-diagnosis-hypo2.html\">Condition/condition-example-diagnosis-hypo2</a></p><p><b>status</b>: complete</p><p><b>type</b>: individual</p><p><b>measure</b>: <a href=\"http://www.cdc.gov/nhsn/fhirportal/dqm/ig/Measure/NHSNdQMAcuteCareHospitalInitialPopulation\">http://www.cdc.gov/nhsn/fhirportal/dqm/ig/Measure/NHSNdQMAcuteCareHospitalInitialPopulation|1.0.0</a></p><p><b>subject</b>: <a href=\"Patient-patient-example-hypo.html\">Patient/patient-example-hypo</a> &quot; HYPO&quot;</p><p><b>date</b>: 2022-11-15 21:03:38+0000</p><p><b>reporter</b>: <a href=\"Organization-organization-example-submitting-organization.html\">Organization/organization-example-submitting-organization</a> &quot;Example NHSN Submitter&quot;</p><p><b>period</b>: 2022-08-01 00:00:00+0000 --&gt; 2022-08-31 23:59:59+0000</p><p><b>improvementNotation</b>: Increased score indicates improvement <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"http://terminology.hl7.org/5.0.0/CodeSystem-measure-improvement-notation.html\">MeasureImprovementNotation</a>#increase)</span></p><blockquote><p><b>group</b></p><h3>Populations</h3><table class=\"grid\"><tr><td style=\"display: none\">-</td><td><b>Extension</b></td><td><b>Code</b></td><td><b>Count</b></td></tr><tr><td style=\"display: none\">*</td><td/><td>Initial Population <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"http://terminology.hl7.org/5.0.0/CodeSystem-measure-population.html\">MeasurePopulationType</a>#initial-population)</span></td><td>1</td></tr></table><p><b>measureScore</b>: </p></blockquote><p><b>evaluatedResource</b>: </p><ul><li><a href=\"Observation-observation-example-hypo-lab-hypo1.html\">Observation/observation-example-hypo-lab-hypo1</a></li><li><a href=\"Encounter-encounter-example-hypo-hypo.html\">Encounter/encounter-example-hypo-hypo</a></li><li><a href=\"Observation-observation-example-hypo-lab-hypo2.html\">Observation/observation-example-hypo-lab-hypo2</a></li><li><a href=\"Observation-observation-example-hypo-lab-hypo3.html\">Observation/observation-example-hypo-lab-hypo3</a></li><li><a href=\"Observation-observation-example-hypo-lab-hypo4.html\">Observation/observation-example-hypo-lab-hypo4</a></li><li><a href=\"Medication-medication-example-hypo-hypo1.html\">Medication/medication-example-hypo-hypo1</a></li><li><a href=\"Patient-patient-example-hypo.html\">Patient/patient-example-hypo</a> &quot; HYPO&quot;</li><li><a href=\"Medication-medication-example-hypo-hypo2.html\">Medication/medication-example-hypo-hypo2</a></li><li><a href=\"MedicationRequest-medicationrequest-example-hypo-hypo1.html\">MedicationRequest/medicationrequest-example-hypo-hypo1</a></li><li><a href=\"Observation-observation-example-hypo-lab-hypo5.html\">Observation/observation-example-hypo-lab-hypo5</a></li><li><a href=\"MedicationRequest-medicationrequest-example-hypo-hypo2.html\">MedicationRequest/medicationrequest-example-hypo-hypo2</a></li><li><a href=\"Observation-observation-example-hypo-lab-hypo6.html\">Observation/observation-example-hypo-lab-hypo6</a></li><li><a href=\"Observation-observation-example-hypo-lab-hypo7.html\">Observation/observation-example-hypo-lab-hypo7</a></li><li><a href=\"Condition-condition-example-diagnosis-hypo1.html\">Condition/condition-example-diagnosis-hypo1</a></li><li><a href=\"Medication-medication-example-hypo-hypo3.html\">Medication/medication-example-hypo-hypo3</a></li><li><a href=\"MedicationRequest-medicationrequest-example-hypo-hypo3.html\">MedicationRequest/medicationrequest-example-hypo-hypo3</a></li><li><a href=\"Observation-observation-example-hypo-lab-hypo8.html\">Observation/observation-example-hypo-lab-hypo8</a></li><li><a href=\"MedicationRequest-medicationrequest-example-hypo-hypo4.html\">MedicationRequest/medicationrequest-example-hypo-hypo4</a></li><li><a href=\"Medication-medication-example-hypo-hypo4.html\">Medication/medication-example-hypo-hypo4</a></li><li><a href=\"Condition-condition-example-diagnosis-hypo2.html\">Condition/condition-example-diagnosis-hypo2</a></li></ul></div>"
* extension[0].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-measureScoring"
* extension[=].valueCodeableConcept = $measure-scoring#cohort
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description"
* extension[=].valueString = "The Hypoglycemia Initial Population includes all inpatient encounters (including ED/Observation visits that end within one hour of the start of the inpatient encounter) during the measurement period for patients of all ages in which at least one diabetic medication was ordered or administered during the encounter."
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-initial-population-encounters"
* extension[=].valueReference = Reference(Encounter/encounter-example-hypo-hypo)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo3)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo4)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication"
* extension[=].valueReference = Reference(Medication/medication-example-hypo-hypo1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-minimal-patient"
* extension[=].valueReference = Reference(Patient/patient-example-hypo)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication"
* extension[=].valueReference = Reference(Medication/medication-example-hypo-hypo2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(MedicationRequest/medicationrequest-example-hypo-hypo1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo5)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(MedicationRequest/medicationrequest-example-hypo-hypo2)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo6)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo7)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-condition-during-encounter"
* extension[=].valueReference = Reference(Condition/condition-example-diagnosis-hypo1)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication"
* extension[=].valueReference = Reference(Medication/medication-example-hypo-hypo3)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(MedicationRequest/medicationrequest-example-hypo-hypo3)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-hypo8)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(MedicationRequest/medicationrequest-example-hypo-hypo4)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication"
* extension[=].valueReference = Reference(Medication/medication-example-hypo-hypo4)
* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-condition-during-encounter"
* extension[=].valueReference = Reference(Condition/condition-example-diagnosis-hypo2)
* status = #complete
* type = #individual
* measure = "http://www.cdc.gov/nhsn/fhirportal/dqm/ig/Measure/NHSNdQMAcuteCareHospitalInitialPopulation|1.0.0-cibuild"
* subject = Reference(Patient/patient-example-hypo)
* date = "2022-11-15T21:03:38+00:00"
* reporter = Reference(organization-example-submitting-organization)
* period.start = "2022-08-01T00:00:00+00:00"
* period.end = "2022-08-31T23:59:59+00:00"
* improvementNotation = $measure-improvement-notation#increase
//* group.measureScore.extension.url = "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
//* group.measureScore.extension.valueCode = #unknown
* group.population.extension.url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description"
* group.population.extension.valueString = "All inpatient encounters (including ED/Observation visits that end within one hour of the start of the inpatient encounter) during the measurement period for patients of all ages in which at least one diabetic medication was ordered or administered during the encounter."
* group.population.code = $measure-population#initial-population "Initial Population"
* group.population.count = 1
* evaluatedResource[0] = Reference(Observation/observation-example-hypo-lab-hypo1)
* evaluatedResource[+] = Reference(Encounter/encounter-example-hypo-hypo)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-hypo2)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-hypo3)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-hypo4)
* evaluatedResource[+] = Reference(Medication/medication-example-hypo-hypo1)
* evaluatedResource[+] = Reference(Patient/patient-example-hypo)
* evaluatedResource[+] = Reference(Medication/medication-example-hypo-hypo2)
* evaluatedResource[+] = Reference(MedicationRequest/medicationrequest-example-hypo-hypo1)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-hypo5)
* evaluatedResource[+] = Reference(MedicationRequest/medicationrequest-example-hypo-hypo2)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-hypo6)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-hypo7)
* evaluatedResource[+] = Reference(Condition/condition-example-diagnosis-hypo1)
* evaluatedResource[+] = Reference(Medication/medication-example-hypo-hypo3)
* evaluatedResource[+] = Reference(MedicationRequest/medicationrequest-example-hypo-hypo3)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-hypo8)
* evaluatedResource[+] = Reference(MedicationRequest/medicationrequest-example-hypo-hypo4)
* evaluatedResource[+] = Reference(Medication/medication-example-hypo-hypo4)
* evaluatedResource[+] = Reference(Condition/condition-example-diagnosis-hypo2)