ValueSet: BedCapacityVS
Id: nhsn-safr-bed-capacity-codes
Title: "Bed Capacity Codes ValueSet"
Description: "Codes for bed capacity reporting"
* ^experimental = false
* ^status = #active
* http://loinc.org#112511-1 "Adult emergency department beds-admitted [#] Facility Occupied"
* http://loinc.org#112512-9 "Adult emergency department beds [#] Facility Occupied.total"
* http://loinc.org#112577-2 "Adult inpatient beds [#] Facility Occupied.total"
* http://loinc.org#112576-4 "Adult inpatient beds [#] Facility Unoccupied.total"
* http://loinc.org#112573-1 "Adult intensive care unit-level of care beds [#] Facility Occupied"
* http://loinc.org#112575-6 "Adult intensive care unit beds [#] Facility Occupied"
* http://loinc.org#112574-9 "Adult intensive care unit beds [#] Facility Unoccupied"
* http://loinc.org#112568-1 "Adult medicine telemetry and general acute care beds [#] Facility Occupied"
* http://loinc.org#112567-3 "Adult medicine telemetry and general acute care beds [#] Facility Unoccupied"
* http://loinc.org#112572-3 "Adult non-intensive care unit beds [#] Facility Occupied"
* http://loinc.org#112571-5 "Adult non-intensive care unit beds [#] Facility Unoccupied"
* http://loinc.org#112566-5 "Adult observation beds [#] Facility Occupied"
* http://loinc.org#112565-7 "Adult observation beds [#] Facility Unoccupied"
* http://loinc.org#112570-7 "Adult progressive care unit beds [#] Facility Occupied"
* http://loinc.org#112569-9 "Adult progressive care unit beds [#] Facility Unoccupied"
* http://loinc.org#112579-8 "All inpatient beds [#] Facility Occupied"
* http://loinc.org#112578-0 "All inpatient beds [#] Facility Unoccupied"
* http://loinc.org#112516-0 "Burn beds [#] Facility Occupied"
* http://loinc.org#112515-2 "Burn beds [#] Facility Unoccupied"
* http://loinc.org#112507-9 "Emergency department beds-admitted [#] Facility Occupied.total"
* http://loinc.org#112508-7 "Emergency department beds [#] Facility Occupied.total"
* http://loinc.org#112506-1 "Facility context-entire or subunit for reporting"
* http://loinc.org#112514-5 "Negative pressure beds [#] Facility Occupied"
* http://loinc.org#112513-7 "Negative pressure beds [#] Facility Unoccupied"
* http://loinc.org#112509-5 "Pediatric emergency department beds-admitted [#] Facility Occupied"
* http://loinc.org#112510-3 "Pediatric emergency department beds [#] Facility Occupied.total"
* http://loinc.org#112564-0 "Pediatric inpatient beds [#] Facility Occupied.total"
* http://loinc.org#112563-2 "Pediatric inpatient beds [#] Facility Unoccupied.total"
* http://loinc.org#112560-8 "Pediatric intensive care unit-level of care beds [#] Facility Occupied"
* http://loinc.org#112562-4 "Pediatric intensive care unit beds [#] Facility Occupied"
* http://loinc.org#112561-6 "Pediatric intensive care unit beds [#] Facility Unoccupied"
* http://loinc.org#112555-8 "Pediatric medicine telemetry and general acute care beds [#] Facility Occupied"
* http://loinc.org#112554-1 "Pediatric medicine telemetry and general acute care beds [#] Facility Unoccupied"
* http://loinc.org#112559-0 "Pediatric non-intensive care unit beds [#] Facility Occupied"
* http://loinc.org#112558-2 "Pediatric non-intensive care unit beds [#] Facility Unoccupied"
* http://loinc.org#112553-3 "Pediatric observation beds [#] Facility Occupied"
* http://loinc.org#112552-5 "Pediatric observation beds [#] Facility Unoccupied"
* http://loinc.org#112557-4 "Pediatric progressive care unit beds [#] Facility Occupied"
* http://loinc.org#112556-6 "Pediatric progressive care unit beds [#] Facility Unoccupied"
* http://loinc.org#112531-9 "Specialty adult psychiatric beds [#] Facility Occupied"
* http://loinc.org#112530-1 "Specialty adult psychiatric beds [#] Facility Unoccupied"
* http://loinc.org#112551-7 "Specialty beds [#] Facility Occupied.total"
* http://loinc.org#112550-9 "Specialty beds [#] Facility Unoccupied.total"
* http://loinc.org#112533-5 "Specialty neonatal intensive care unit-level 1 [#] Facility Occupied"
* http://loinc.org#112532-7 "Specialty neonatal intensive care unit-level 1 [#] Facility Unoccupied"
* http://loinc.org#112537-6 "Specialty neonatal intensive care unit-level 2 [#] Facility Occupied"
* http://loinc.org#112536-8 "Specialty neonatal intensive care unit-level 2 [#] Facility Unoccupied"
* http://loinc.org#112540-0 "Specialty neonatal intensive care unit-level 3 plus beds [#] Facility Occupied"
* http://loinc.org#112541-8 "Specialty neonatal intensive care unit-level 3 plus beds [#] Facility Unoccupied"
* http://loinc.org#112538-4 "Specialty neonatal intensive care unit-level 3 [#] Facility Occupied"
* http://loinc.org#112539-2 "Specialty neonatal intensive care unit-level 3 [#] Facility Unoccupied"
* http://loinc.org#112543-4 "Specialty neonatal intensive care unit-level 4 beds [#] Facility Occupied"
* http://loinc.org#112542-6 "Specialty neonatal intensive care unit-level 4 beds [#] Facility Unoccupied"
* http://loinc.org#112545-9 "Specialty neonatal intensive care unit beds [#] Facility Occupied.total"
* http://loinc.org#112544-2 "Specialty neonatal intensive care unit beds [#] Facility Unoccupied.total"
* http://loinc.org#112549-1 "Specialty non-crib beds [#] Facility Occupied"
* http://loinc.org#112548-3 "Specialty non-crib beds [#] Facility Unoccupied"
* http://loinc.org#112535-0 "Specialty nursery beds [#] Facility Occupied"
* http://loinc.org#112534-3 "Specialty nursery beds [#] Facility Unoccupied"
* http://loinc.org#112547-5 "Specialty obstetric beds [#] Facility Occupied"
* http://loinc.org#112546-7 "Specialty obstetric beds [#] Facility Unoccupied"
* http://loinc.org#112529-3 "Specialty pediatric psychiatric beds [#] Facility Occupied"
* http://loinc.org#112528-5 "Specialty pediatric psychiatric beds [#] Facility Unoccupied"
* http://loinc.org#112527-7 "Specialty rehabilitation beds [#] Facility Occupied"
* http://loinc.org#112526-9 "Specialty rehabilitation beds [#] Facility Unoccupied"
* http://loinc.org#112525-1 "Surge-active [#] Facility Occupied.total"
* http://loinc.org#112524-4 "Surge-active [#] Facility Unoccupied.total"
* http://loinc.org#112523-6 "Surge-inactive [#] Facility Unoccupied.total"
* http://loinc.org#112522-8 "Surge intensive care unit beds-active [#] Facility Occupied"
* http://loinc.org#112521-0 "Surge intensive care unit beds-active [#] Facility Unoccupied"
* http://loinc.org#112520-2 "Surge intensive care unit beds-inactive [#] Facility Unoccupied"
* http://loinc.org#112519-4 "Surge non-intensive care unit beds-active [#] Facility Occupied"
* http://loinc.org#112518-6 "Surge non-intensive care unit beds-active [#] Facility Unoccupied"
* http://loinc.org#112517-8 "Surge non-intensive care unit beds-inactive [#] Facility Unoccupied"