Instance: measurereport-example-ach-daily-negativepcr
InstanceOf: DEQMIndividualMeasureReportProfile
Title: "MeasureReport - Example Individual ACH Daily Negative PCR"
Description: "MeasureReport - Example Individual ACH Daily Negative PCR"
Usage: #example
* meta.profile = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/indv-measurereport-deqm"
* identifier.system = "http://example.org/fhir/measurereport/id"
* identifier.value = "123456789-pass1"
//* extension[0].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-measureScoring"
* extension[scoring][+].valueCodeableConcept = $measure-scoring#cohort
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description"
//* extension[=].valueString = "The RPS Initial Population includes all encounters for patients of any age in an ED, observation, or inpatient location or all encounters for patients of any age with an ED, observation, inpatient, or short stay status during the measurement period."
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-minimal-patient"
* extension[supplementalData][=].valueReference = Reference(patient-example-ach-daily-negativepcr)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-encounter"
* extension[supplementalData][=].valueReference = Reference(encounter-example-ach-daily-negativepcr-1)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-encounter"
* extension[supplementalData][=].valueReference = Reference(encounter-example-ach-daily-negativepcr-2)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-coverage"
* extension[supplementalData][=].valueReference = Reference(coverage-example-ach-daily-negativepcr)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-condition"
* extension[supplementalData][=].valueReference = Reference(condition-example-diagnosis-ach-daily-negativepcr)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-medication-administration"
* extension[supplementalData][=].valueReference = Reference(medadmin-example-ach-daily-negativepcr)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-medication-request"
* extension[supplementalData][=].valueReference = Reference(medicationrequest-example-ach-daily-negativepcr)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-observation-lab-category"
* extension[supplementalData][=].valueReference = Reference(lab-observation-example-ach-daily-negativepcr-1)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-observation-lab-category"
* extension[supplementalData][=].valueReference = Reference(lab-observation-example-ach-daily-negativepcr-2)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-service-request"
* extension[supplementalData][=].valueReference = Reference(servicerequest-example-ach-daily-negativepcr-covid-1)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-service-request"
* extension[supplementalData][=].valueReference = Reference(servicerequest-example-ach-daily-negativepcr-covid-2)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-specimen"
* extension[supplementalData][=].valueReference = Reference(specimen-example-ach-daily-negativepcr-1)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-specimen"
* extension[supplementalData][=].valueReference = Reference(specimen-example-ach-daily-negativepcr-2)
//* extension[+].url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.supplementalDataElement.reference"
//* extension[supplementalData][+].valueReference.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-criteriaReference"
* extension[supplementalData][+].valueReference.extension[criteriaReference].valueString = "sde-procedure"
* extension[supplementalData][=].valueReference = Reference(procedure-example-ach-daily-negativepcr-intubation)
* status = #complete
* type = #individual
* measure = "http://www.cdc.gov/nhsn/fhirportal/dqm/ig/Measure/NHSNAcuteCareHospitalDailyInitialPopulation|2.0.0-cibuild"
* subject = Reference(patient-example-ach-daily-negativepcr)
* date = "2024-01-06T21:04:29.481+00:00"
* reporter = Reference(organization-example-submitting-organization)
* period.start = "2024-01-05T00:00:00.000+00:00"
* period.end = "2024-01-06T00:00:00.000+00:00"
* improvementNotation = $measure-improvement-notation#increase
//* group.measureScore.extension.url = "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
//* group.measureScore.extension.valueCode = #unknown
//* group.population.extension.url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description"
//* group.population.extension.valueString = "All inpatient encounters (including ED/Observation visits that end within one hour of the start of the inpatient encounter) during the measurement period for patients of all ages in which at least one diabetic medication was ordered or administered during the encounter."
* group.population.code = $measure-population#initial-population "Initial Population"
* group.population.count = 1
* evaluatedResource[0] = Reference(patient-example-ach-daily-negativepcr)
* evaluatedResource[+] = Reference(encounter-example-ach-daily-negativepcr-1)
* evaluatedResource[+] = Reference(encounter-example-ach-daily-negativepcr-2)
* evaluatedResource[+] = Reference(coverage-example-ach-daily-negativepcr)
* evaluatedResource[+] = Reference(condition-example-diagnosis-ach-daily-negativepcr)
* evaluatedResource[+] = Reference(medadmin-example-ach-daily-negativepcr)
* evaluatedResource[+] = Reference(medicationrequest-example-ach-daily-negativepcr)
* evaluatedResource[+] = Reference(lab-observation-example-ach-daily-negativepcr-1)
* evaluatedResource[+] = Reference(lab-observation-example-ach-daily-negativepcr-2)
* evaluatedResource[+] = Reference(servicerequest-example-ach-daily-negativepcr-covid-1)
* evaluatedResource[+] = Reference(servicerequest-example-ach-daily-negativepcr-covid-2)
* evaluatedResource[+] = Reference(specimen-example-ach-daily-negativepcr-1)
* evaluatedResource[+] = Reference(specimen-example-ach-daily-negativepcr-2)
* evaluatedResource[+] = Reference(procedure-example-ach-daily-negativepcr-intubation)