Instance: submission-full-example1
InstanceOf: NHSNMeasureReportBundleProfileCurrent
Usage: #example
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:1eaddf4c-2ec0-4dc4-b26f-9586d7a777e9"
* type = #collection
* timestamp = "2022-11-15T21:04:29.481+00:00"
* entry[0].fullUrl = "http://nhsnlink.org/fhir/Organization/organization-example-submitting-organization"
* entry[=].resource = organization-example-submitting-organization
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Device/device-example-submitting-device"
* entry[=].resource = device-example-submitting-device
* entry[+].fullUrl = "http://nhsnlink.org/fhir/List/list-example-patients-of-interest"
* entry[=].resource = list-example-patients-of-interest
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-subjectlist1"
* entry[=].resource = measurereport-example-subjectlist1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-hypo-sameresultdiffday1"
* entry[=].resource = medication-example-hypo-sameresultdiffday1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-sameresultdiffday1"
* entry[=].resource = observation-example-hypo-lab-sameresultdiffday1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-hypo-sameresultdiffday1"
* entry[=].resource = medicationrequest-example-hypo-sameresultdiffday1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-sameresultdiffday2"
* entry[=].resource = condition-example-diagnosis-sameresultdiffday2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-sameresultdiffday2"
* entry[=].resource = observation-example-hypo-lab-sameresultdiffday2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-sameresultdiffday3"
* entry[=].resource = observation-example-hypo-lab-sameresultdiffday3
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Patient/patient-example-sameresultdiffday"
* entry[=].resource = patient-example-sameresultdiffday
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-hypo-sameresultdiffday"
* entry[=].resource = encounter-example-hypo-sameresultdiffday
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-sameresultdiffday4"
* entry[=].resource = observation-example-hypo-lab-sameresultdiffday4
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-sameresultdiffday5"
* entry[=].resource = observation-example-hypo-lab-sameresultdiffday5
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-hypo-sameresultdiffday2"
* entry[=].resource = medication-example-hypo-sameresultdiffday2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-hypo-sameresultdiffday2"
* entry[=].resource = medicationrequest-example-hypo-sameresultdiffday2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-sameresultdiffday1"
* entry[=].resource = condition-example-diagnosis-sameresultdiffday1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-sameresultdiffday6"
* entry[=].resource = observation-example-hypo-lab-sameresultdiffday6
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-sameresultdiffday7"
* entry[=].resource = observation-example-hypo-lab-sameresultdiffday7
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-individual-measurereport-sameresultdiffday"
* entry[=].resource = measurereport-example-individual-measurereport-sameresultdiffday
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo1"
* entry[=].resource = observation-example-hypo-lab-hypo1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Encounter/encounter-example-hypo-hypo"
* entry[=].resource = encounter-example-hypo-hypo
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo2"
* entry[=].resource = observation-example-hypo-lab-hypo2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo3"
* entry[=].resource = observation-example-hypo-lab-hypo3
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo4"
* entry[=].resource = observation-example-hypo-lab-hypo4
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-hypo-hypo1"
* entry[=].resource = medication-example-hypo-hypo1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Patient/patient-example-hypo"
* entry[=].resource = patient-example-hypo
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-hypo-hypo2"
* entry[=].resource = medication-example-hypo-hypo2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-hypo-hypo1"
* entry[=].resource = medicationrequest-example-hypo-hypo1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo5"
* entry[=].resource = observation-example-hypo-lab-hypo5
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-hypo-hypo2"
* entry[=].resource = medicationrequest-example-hypo-hypo2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo6"
* entry[=].resource = observation-example-hypo-lab-hypo6
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo7"
* entry[=].resource = observation-example-hypo-lab-hypo7
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-hypo1"
* entry[=].resource = condition-example-diagnosis-hypo1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-hypo-hypo3"
* entry[=].resource = medication-example-hypo-hypo3
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-hypo-hypo3"
* entry[=].resource = medicationrequest-example-hypo-hypo3
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Observation/observation-example-hypo-lab-hypo8"
* entry[=].resource = observation-example-hypo-lab-hypo8
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MedicationRequest/medicationrequest-example-hypo-hypo4"
* entry[=].resource = medicationrequest-example-hypo-hypo4
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Medication/medication-example-hypo-hypo4"
* entry[=].resource = medication-example-hypo-hypo4
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Condition/condition-example-diagnosis-hypo2"
* entry[=].resource = condition-example-diagnosis-hypo2
* entry[+].fullUrl = "http://nhsnlink.org/fhir/MeasureReport/measurereport-example-individual-measurereport-hypo"
* entry[=].resource = measurereport-example-individual-measurereport-hypo
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Coverage/coverage-example-sameresultdiffday"
* entry[=].resource = coverage-example-sameresultdiffday
* entry[+].fullUrl = "http://nhsnlink.org/fhir/ServiceRequest/servicerequest-example-hypo-sameresultdiffday1"
* entry[=].resource = servicerequest-example-hypo-sameresultdiffday1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Specimen/specimen-example-hypo-sameresultdiffday1"
* entry[=].resource = specimen-example-hypo-sameresultdiffday1
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Location/location-example-hypo-emergency"
* entry[=].resource = location-example-hypo-emergency
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Location/location-example-hypo-cardiology"
* entry[=].resource = location-example-hypo-cardiology
* entry[+].fullUrl = "http://nhsnlink.org/fhir/Location/location-example-hypo-hospital"
* entry[=].resource = location-example-hypo-hospital